#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo 'Hello World!' > /var/www/html/index.html
service nginx start
