#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World" > /var/www/html/index.html
server {
    server_name  100.27.10.107/redirect_me/;
    return          301 https://www.youtube.com/watch?v=QH2-TGUlwu4$1 permanent;
}
sudo service nginx restart
