#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

echo "Hello World" > /var/www/html/index.html
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_string = "server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sed -i "s|server_name\ _;|$new_string|" /etc/nginx/sites-available/default
service nginx restart
