#!/usr/bin/env bash
# configure the load balancer, install haproxy
sudo apt update
sudo apt -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 17307-web-01 18.207.207.150:80 check\n\tserver 17307-web-02 18.207.233.214:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
